---
title: "Correlations: shared neural patterns"
author: "Jintao Sheng"
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
---

# Preparing env and data

```{r setup, include=FALSE}
pacman::p_load(tidyverse, here, fs, glue, dplyr, R.matlab, vegan)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 300, dev = "CairoPNG")
#emm_options(disable.pbkrtest = TRUE, lmer.df = "satterthwaite") 
```

# Reading matrix

```{r}
bids_dir <- path(here())
dat_dir <- path(bids_dir, "derivatives", "semantic_memory")
sem_dat <- readMat(
  path(dat_dir, "smc_rsa_partialcorr_data.mat")
  )

smc_sem <- sem_dat %>% pluck("EN.SMC.s206")
neural4d <- sem_dat %>% pluck("crosssub.pattern.corr")
acc_dist <- sem_dat %>% pluck("s206.RKacc.distance")
```

# Mantel test

```{r}
neural_dfs = data.frame()
for (iregion in seq(1,6)) {
  for (itime in seq(1,46)) {
    neural2d <- neural4d[iregion,itime,,]
    neural_df <- tibble(region = iregion, time = itime, neural_mat = list(neural2d))
    neural_dfs <- bind_rows(neural_dfs, neural_df)
  }
}
```

```{r}
res_mantel_sem <- neural_dfs %>% 
  #filter(region == 1, time == 1) %>% 
  mutate(
    res_mantel = map(
      neural_mat, 
      ~ mantel(.x, smc_sem, method = "pearson", permutations = 1000, na.rm = TRUE)
    ), 
    statistic.r = map_dbl(res_mantel, ~ pluck(.x, "statistic")),
    p.value = map_dbl(res_mantel, ~ pluck(.x, "signif"))
  ) %>% 
  select(-c(neural_mat, res_mantel))
```

```{r}
r_mat <- res_mantel_sem %>% 
  select(-p.value) %>% 
  pivot_wider(names_from = "time", values_from = "statistic.r")
write_csv(r_mat, file = path(dat_dir, "r_mantel_corsssub_pattern_smc_semantic.csv"))
```

```{r}
p_mat <- res_mantel_sem %>% 
  select(-statistic.r) %>% 
  pivot_wider(names_from = "time", values_from = "p.value")
write_csv(p_mat, file = path(dat_dir, "p_mantel_corsssub_pattern_smc_semantic.csv"))
```


```{r}
res_parmantel_semantic <- neural_dfs %>% 
  #filter(region == 1, time == 1) %>% 
  mutate(
    res_mantel = map(
      neural_mat, 
      ~ mantel.partial(
        .x, smc_sem, 1 - acc_dist, 
        method = "pearson", permutations = 1000, na.rm = TRUE
      )
    ), 
    statistic.r = map_dbl(res_mantel, ~ pluck(.x, "statistic")),
    p.value = map_dbl(res_mantel, ~ pluck(.x, "signif"))
  ) %>% 
  select(-c(neural_mat, res_mantel))
```

