---
title: "Comparing RR verse FF"
author: "Jintao Sheng"
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
---

## Preparing env and data

```{r setup, include=FALSE}
pacman::p_load(tidyverse, here, fs, glue, lmerTest, emmeans, ggsci, ggthemes, ggpubr, extrafont, patchwork)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 300, dev = "CairoPNG")
```


```{r}
bids_dir <- path(here())
deriv_dir <- path(bids_dir, "derivatives")
demean_id <- "nodemean"
load(
  file = path(
    bids_dir, "code", "08_stats_roi_add", "data", 
    str_glue("simi_wics_mean_subjpairs_roisadd_{demean_id}_fisherz.RData")
  )
) #simi_wics_mean
```

```{r}
tmp_mat_ff <- simi_wics_mean %>% 
  filter(memory_score == 0) %>% 
  group_nest(roi_name, memory_score) %>% 
  mutate(
    mat = map(
      data, 
      ~ pivot_wider(.x, names_from = subj_id2, values_from = similarity, values_fill = 0) %>% 
        dplyr::select(-subj_id1) %>% 
        mutate(`2001` = 0, .before = 1L) %>% 
        as.matrix() %>% rbind(0)
    ),
    simi_mat = map(mat, ~ .x + t(.x))
  ) %>% 
  dplyr::select(roi_name, simi_mat)

tmp_list_ff <- deframe(tmp_mat_ff)

tmp_mat_rr <- simi_wics_mean %>% 
  filter(memory_score == 1) %>% 
  group_nest(roi_name, memory_score) %>% 
  mutate(
    mat = map(
      data, 
      ~ pivot_wider(.x, names_from = subj_id2, values_from = similarity, values_fill = 0) %>% 
        dplyr::select(-subj_id1) %>% 
        mutate(`2001` = 0, .before = 1L) %>% 
        as.matrix() %>% rbind(0)
    ),
    simi_mat = map(mat, ~ .x + t(.x))
  ) %>% 
  dplyr::select(roi_name, simi_mat)

tmp_list_rr <- deframe(tmp_mat_rr)

R.matlab::writeMat(
  path(bids_dir, "code", "08_stats_roi_add", "data", "compare_rrvsff_subjpairs_matrix.mat"), 
  ff = tmp_list_ff, rr = tmp_list_rr
  )
```

```{r}
res_rr_ff_perm <- read_csv(
  path(bids_dir, "code", "08_stats_roi_add", "results", "res_stats_rr_vs_ff_perm1w.csv"),
  show_col_types = F
) %>% 
  mutate(p.adj = p.adjust(p_value, method = "fdr"))

res_rr_ff_perm %>% knitr::kable(digits = 3)
```

```{r}
res_rr_ff_perm %>% 
  filter(
    roi == "bANG_schaefer2018" | roi =="bHIP" | roi == "bVVC" | roi == "PMC" | 
      roi == "vmPFC" | roi == "bIFG"
  ) %>% 
  mutate(roi = if_else(roi == "bANG_schaefer2018", "bANG", roi)) %>% 
  mutate(p.adj = p.adjust(p_value, method = "fdr"))
```


```{r fig.height=6.8, fig.width=10}
#tmp <- res_rr_ff_perm %>% filter(p.adj <= 0.05)
simi_wics_mean %>% 
  rename(roi = roi_name) %>% 
  filter(
    roi == "bANG_schaefer2018" | roi =="bHIP" | roi == "bVVC" | roi == "PMC" | 
      roi == "vmPFC" | roi == "bIFG"
  ) %>% 
  mutate(roi = if_else(roi == "bANG_schaefer2018", "bANG", roi)) %>%  
  mutate(memory_score = case_when(memory_score == "1" ~ "RR", T ~ "FF")) %>% 
  mutate(roi = gsub("b", "", as.character(roi))) %>% 
  group_by(roi, memory_score) %>% 
  summarise(mean_se(similarity), .groups = "drop") %>% 
  ungroup() %>% 
  mutate(memory_score = factor(memory_score, c("RR", "FF"))) %>% 
  #mutate(roi = fct_reorder(roi, desc(y))) %>%
  mutate(roi = factor(roi, c("VVC", "PMC", "HIP", "ANG", "IFG", "vmPFC"))) %>% 
  ggplot(aes(roi, y, ymax = ymax, ymin = ymin, fill = memory_score)) +
  geom_col(position = position_dodge(width = 0.9), width = 0.8) +
  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3, size = 1) +
  scale_fill_manual(values = c("#C91E12", "#FDC58E")) +
  #coord_cartesian(ylim = c(0, 0.03)) +
  #scale_y_continuous(breaks = seq(0,0.1,0.03)) +
  labs(y = "ISPS", x = "", fill = "", color = "") +
  theme_pubr(base_size = 32, base_family = "Gill Sans MT") +
  theme(
    axis.line = element_line(size = 1.5),
    legend.text = element_text(size = 34)
  )
```

```{r}
res_rr_ff_perm %>% 
  filter(
    roi == "lANG" | roi == "rANG" | roi =="lHIP" | roi =="rHIP" | roi == "lVVC" | 
      roi == "rVVC" | roi == "PMC" | roi == "vmPFC" | roi == "lIFG" | roi == "rIFG"
  ) %>% 
  mutate(p.adj = p.adjust(p_value, method = "fdr"))
```


```{r fig.height=6, fig.width=12}
#tmp <- res_rr_ff_perm %>% filter(p.adj <= 0.05)
simi_wics_mean %>% 
  rename(roi = roi_name) %>% 
  filter(
    roi == "lANG" | roi == "rANG" | roi =="lHIP" | roi =="rHIP" | roi == "lVVC" | 
      roi == "rVVC" | roi == "PMC" | roi == "vmPFC" | roi == "lIFG" | roi == "rIFG"
  ) %>% 
  #semi_join(tmp, by = "roi") %>% 
  mutate(memory_score = case_when(memory_score == "1" ~ "RR", T ~ "FF")) %>% 
  group_by(roi, memory_score) %>% 
  summarise(mean_se(similarity), .groups = "drop") %>% 
  ungroup() %>% 
  mutate(memory_score = factor(memory_score, c("RR", "FF"))) %>% 
  #mutate(roi = fct_reorder(roi, desc(y))) %>%
  mutate(roi = factor(roi, c("lVVC", "rVVC", "PMC", "lHIP", "rHIP", "lANG", "rANG", "lIFG", "rIFG", "vmPFC"))) %>% 
  ggplot(aes(roi, y, ymax = ymax, ymin = ymin, fill = memory_score)) +
  geom_col(position = position_dodge(width = 0.9), width = 0.8) +
  geom_errorbar(position = position_dodge(width = 0.9), width = 0.3, size = 1) +
  scale_fill_manual(values = c("#C91E12", "#FDC58E")) +
  #coord_cartesian(ylim = c(0, 0.03)) +
  #scale_y_continuous(breaks = seq(0,0.1,0.03)) +
  labs(y = "Pattern Similarity", x = "", fill = "", color = "") +
  theme_pubr(base_size = 30, base_family = "Gill Sans MT") +
  theme(
    axis.line = element_line(size = 1),
    legend.text = element_text(size = 32)
  )
```
